---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openobserve
  namespace: openobserve
spec:
  encryptedData:
    ZO_ROOT_USER_EMAIL: AgAax1J3CeSb0eb28/KED6VvSxallGxHL07FvnlPG0MCmRXNQTmZxDv3/jt2+vcliLiPKJQDEYITpF4Ev7KVuvbaOdr6uJmAvpiG22Y/iJjxN9Fa9+oIcuZXjrqGWFFYxLXLCaF3ot4Bf/9uVup8w7DcZ6wHQwfdxL9NNv4ZwJgEGc3c+35YTHd3G/+MFVdJRQK9m91LXcNHFTcQBv8dsxq1cE5qAXk735Sc+Rpm2F1OUTl3h0EwAtm9y5jutTGvu+GlnsSrEqJwJMzGefWL/vQHHyfgyoB13L2CnARyy1rts3pbmqm/o2h9DDTB939Thj/sFesRF8zGB4G3Yr98dkkMmlD9AtovFm/T5nQwVjrBEeoDMX5S9CtsgbyqTBf2z1+ZwE4xuUKwRR9djkd9BciDPhqEHQ8j3StmrymLpAL2tHy6uTfVx8DGIOX08rlPw27ZwgBaFgFapkw/WIxguqNvf1wZ9omk7XKfFmIoCadj0OPDFiKJR+ao6yIUVBKUqqdGFr1ENq1IGedrT0m4tmsvMOXK/ZRqINwCo7I6lTc4RMZ7z/i490emaOjBZqwDW1eiZ3SQmlH2l8+WKc7z0OwTaRjBERCmyQIUgpYkue95dxuOhu6tT9k3BJtYxLD4Wv2MvqNECm0+TSUYbGavhqx7eEHiXay/XBx2rq4xLRLOVgH+WN3dMh9tPXJP6HGItoqaSVA6lEwHKF7qOIbd2wh1jZIr9YbxBABB7A==
    ZO_ROOT_USER_PASSWORD: AgBFngV4SJtF80hCSnU6aH/SPIZZ7wLB9PK1x48CPX6xPEekPlx95FTaD92wcG9YoReoonhpQXryY3hoPngCJ04gFbzyTGlpDh1XeZwDg+ccrXS4N3wRomBEunGTBUwxQFn8RTFV8gsInFcTEXwlSrt+VMeTn9HDMtGesdFm2fiP4ZUhI7MAF9JxEWZPQcrLGWbItHGDKx1RTpsvBfukbB2C/7kTyP8L7abDP3G4ZKfZk83XAt85xPIUaeyKIr+wDmEo3gO3dvzWFcaO3clXUNB3poe/Ozm/MYcKRCftDxVpCBDX+1KIqNV6QRtuuTJ4AiFfLmKL9nrZ2SzLtOEnaPSL06JKsK6ekfNuqhmJA2TbVw/ZtnQLMHn1hmtedpTWuX3ENd2wdd8x5XMVsuJOnWxWkAE7quBJSVmOjLnYGK3NPCdiSTj4Z0guxgeVJl8dWvww74AYMGuKip3U4lEEcPy1C6fluZh6lRumzJbjh4KxBPyX0OhPTGaec4F1VA/5JniOuxnmL1nDeRtcdKUB7/yP3VyMxxgTrMXpdGT2/zkZBgieXTnK1jtprsYWOrYoYfJW1r/5O8F0s67ycUHAbE16C5+0kYihruQ2/DoZb7v+Twcn5vDdzhN1J4WQ6tMM72NtmZyw6fTLu7/UCkprVujvQiLgEgKGHzLCX3EpLHEpTQiExaVwdbt401YOdFtmmDjQpkYk4CuvOsZWVw==
  template:
    metadata:
      name: openobserve
      namespace: openobserve
